#!/usr/bin/bash

echo "Running VCS simulation"
which vcs
vcs -full64  -v2005  -f buffer.f -v /opt/ECE_Lib/SAED32_EDK/lib/stdcell_rvt/verilog/saed32nm.v -v  /opt/ECE_Lib/SAED32_EDK/lib/sram/verilog/saed32sram.v -debug_pp
